version: '3.8'

services:
  ros-humble:
    image: ros-humble
    container_name: ros-humble
    build:
      dockerfile: ros.Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
      - ./assignment_package:/home/ros/DNRS_assignment_2/ros2_ws/src/assignment_package
    network_mode: host
    stdin_open: true
    tty: true
